### ISSUE TITLE
Add ability to save gear ? 

### ISSUE THREAD

**Issue by Ladylain** [MrEliasen/BDO-Gear-Calculator#2]
Hi, 

i like your work, and i want to know if you are going to perfect it with a function to save the gear of someone, like maybe with a link ? 

Thanks

**Comment by MrEliasen** [comment]
Hi there,

Sorry about the wait.
I am actually re-doing the whole UI and working on a mobile app version of the calculator with save-load functionality. The web developer version already have save-load, so I might just look into pushing it live while I work on the new re-coded app.

I will give it a look this weekend

Ps. sorry about the long wait for a reply. GitHub gave me no notification of your message, I saw it by "accident".

**Comment by MrEliasen** [comment]
Sorry about the delay, I have just pushed the code live. It was made a couple of months ago and I do not remember why it was not pushed then - might be I did not fully test it.
Bad practise to push it live then? Probably, but I thought i would rather do that now while I work on the app instead of keeping it to myself.

Enjoy!
